from . import views
from django.urls import path

urlpatterns = [
    path('', views.home),
    path('registrarPersona/', views.registrarPersona),
    path('edicionPersona/<int:idPersona>/', views.edicionPersona),
    path('editarPersona/<int:idPersona>/', views.editarPersona),
    path('eliminarPersona/<idPersona>', views.eliminarPersona),
    path('gestionViviendas/', views.gestionViviendas),
    path('gestionViviendas/registrarVivienda/', views.registrarVivienda),
    path('gestionViviendas/edicionVivienda/<idVivienda>', views.edicionVivienda),
    path('gestionViviendas/editarVivienda/', views.editarVivienda),
    path('gestionViviendas/eliminarVivienda/<idVivienda>', views.eliminarVivienda),
    path('gestionBarrios/', views.gestionBarrios),
    path('gestionBarrios/registrarBarrio/', views.registrarBarrio),
    path('gestionBarrios/edicionBarrio/<idBarrio>', views.edicionBarrio),
    path('gestionBarrios/editarBarrio/', views.editarBarrio),
    path('gestionBarrios/eliminarBarrio/<idBarrio>', views.eliminarBarrio),
    path('gestionMunicipios/', views.gestionMunicipios),
    path('gestionMunicipios/registrarMunicipio/', views.registrarMunicipio),
    path('gestionMunicipios/edicionMunicipio/<idMunicipio>', views.edicionMunicipio),
    path('gestionMunicipios/editarMunicipio/', views.editarMunicipio),
    path('gestionMunicipios/eliminarMunicipio/<idMunicipio>', views.eliminarMunicipio),
    path('gestionDepartamentos/', views.gestionDepartamentos),
    path('registrarDepartamento/', views.registrarDepartamento),
    path('gestionDepartamentos/edicionDepartamento/<int:idDepartamento>', views.edicionDepartamento),
    path('gestionDepartamentos/editarDepartamento/', views.editarDepartamento),
    path('gestionDepartamentos/eliminarDepartamento/<int:idDepartamento>', views.eliminarDepartamento),
]
