# Generated by Django 5.0.3 on 2024-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0002_rename_nombre_municipio_nombremunicipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombreMunicipio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
