# Generated by Django 5.0.3 on 2024-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0003_alter_municipio_nombremunicipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='poblacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
