# Generated by Django 5.0.3 on 2024-04-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barrio', '0001_initial'),
        ('Municipio', '0004_alter_municipio_poblacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='idMunicipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Municipio.municipio'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='poblacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
