# Generated by Django 5.0.3 on 2024-04-12 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_delete_tipovivienda_remove_persona_idvivienda_and_more'),
        ('Vivienda', '0002_remove_tipovivienda_poblacion_vivienda_idbarrio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Persona.persona')),
                ('idVivienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Vivienda.vivienda')),
            ],
        ),
    ]
