# Generated by Django 5.0.3 on 2024-04-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vivienda', '0003_personavivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='personavivienda',
            name='propietario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personavivienda',
            name='residente',
            field=models.BooleanField(default=False),
        ),
    ]
