# Generated by Django 5.0.3 on 2024-04-09 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('N', 'No especificado')], default='N', max_length=5)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(default='Not specified', max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No especificado')], default='N', max_length=1)),
                ('edad', models.CharField(default='Not specified', max_length=30)),
                ('idResponsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabezaFamilia', to='Persona.persona')),
            ],
        ),
    ]
