# Generated by Django 5.0.3 on 2024-04-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('idTipoVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('idVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='idVivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Persona.vivienda'),
        ),
    ]
