# Generated by Django 4.1.3 on 2024-04-16 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_delete_tipovivienda_remove_persona_idvivienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
