# Generated by Django 4.1.3 on 2024-04-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0004_remove_persona_edad_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
