# Generated by Django 5.0.3 on 2024-04-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('idBarrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('idTipoVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('idVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(default='Not specified', max_length=10)),
                ('sexo', models.CharField(default='Not specified', max_length=30)),
                ('edad', models.CharField(default='Not specified', max_length=30)),
                ('idResponsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabezaFamilia', to='frontend.persona')),
            ],
        ),
    ]
