# Generated by Django 5.0.3 on 2024-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('idBarrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('idTipoVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('idVivienda', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=45)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='id',
            new_name='idPersona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='email',
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(default='Not specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.CharField(default='Not specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='Not specified', max_length=10),
        ),
    ]
