# Generated by Django 5.0.3 on 2024-03-27 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_barrio_departamento_municipio_tipovivienda_vivienda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre',
            new_name='nombreDepartamento',
        ),
        migrations.AddField(
            model_name='departamento',
            name='idGobernador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.persona'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='poblacion',
            field=models.IntegerField(default=0),
        ),
    ]
