# Generated by Django 5.0.3 on 2024-03-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_nombre_departamento_nombredepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='idGobernador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.persona'),
        ),
    ]
