# Generated by Django 5.0.3 on 2024-03-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_departamento_nombredepartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='idGobernador',
        ),
    ]
