# Generated by Django 5.0.3 on 2024-03-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_departamento_idgobernador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombreDepartamento',
            field=models.CharField(max_length=45),
        ),
    ]
