# Generated by Django 5.0.3 on 2024-04-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_departamento_nombredepartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='idGobernador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.persona'),
        ),
    ]
